package com.july.po;

public class TBloger {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bloger.id
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bloger.username
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bloger.password
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bloger.email
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bloger.hasPermission
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private Integer haspermission;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bloger.id
     *
     * @return the value of t_bloger.id
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bloger.id
     *
     * @param id the value for t_bloger.id
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bloger.username
     *
     * @return the value of t_bloger.username
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bloger.username
     *
     * @param username the value for t_bloger.username
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bloger.password
     *
     * @return the value of t_bloger.password
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bloger.password
     *
     * @param password the value for t_bloger.password
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bloger.email
     *
     * @return the value of t_bloger.email
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bloger.email
     *
     * @param email the value for t_bloger.email
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bloger.hasPermission
     *
     * @return the value of t_bloger.hasPermission
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public Integer getHaspermission() {
        return haspermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bloger.hasPermission
     *
     * @param haspermission the value for t_bloger.hasPermission
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setHaspermission(Integer haspermission) {
        this.haspermission = haspermission;
    }
}