package com.july.po;

import java.util.Date;

public class TBlog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.id
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.title
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.introduction
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private String introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.keyword
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private String keyword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.images
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private String images;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.clickNum
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private Integer clicknum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.commentNum
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private Integer commentnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.agreeNum
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private Integer agreenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.isTop
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private Integer istop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.isRecommend
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private Integer isrecommend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.updateTime
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.addTime
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.status
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.type_id
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.content
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.id
     *
     * @return the value of t_blog.id
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.id
     *
     * @param id the value for t_blog.id
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.title
     *
     * @return the value of t_blog.title
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.title
     *
     * @param title the value for t_blog.title
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.introduction
     *
     * @return the value of t_blog.introduction
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.introduction
     *
     * @param introduction the value for t_blog.introduction
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.keyword
     *
     * @return the value of t_blog.keyword
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.keyword
     *
     * @param keyword the value for t_blog.keyword
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.images
     *
     * @return the value of t_blog.images
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.images
     *
     * @param images the value for t_blog.images
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setImages(String images) {
        this.images = images == null ? null : images.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.clickNum
     *
     * @return the value of t_blog.clickNum
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public Integer getClicknum() {
        return clicknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.clickNum
     *
     * @param clicknum the value for t_blog.clickNum
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setClicknum(Integer clicknum) {
        this.clicknum = clicknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.commentNum
     *
     * @return the value of t_blog.commentNum
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public Integer getCommentnum() {
        return commentnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.commentNum
     *
     * @param commentnum the value for t_blog.commentNum
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setCommentnum(Integer commentnum) {
        this.commentnum = commentnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.agreeNum
     *
     * @return the value of t_blog.agreeNum
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public Integer getAgreenum() {
        return agreenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.agreeNum
     *
     * @param agreenum the value for t_blog.agreeNum
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setAgreenum(Integer agreenum) {
        this.agreenum = agreenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.isTop
     *
     * @return the value of t_blog.isTop
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public Integer getIstop() {
        return istop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.isTop
     *
     * @param istop the value for t_blog.isTop
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setIstop(Integer istop) {
        this.istop = istop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.isRecommend
     *
     * @return the value of t_blog.isRecommend
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public Integer getIsrecommend() {
        return isrecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.isRecommend
     *
     * @param isrecommend the value for t_blog.isRecommend
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setIsrecommend(Integer isrecommend) {
        this.isrecommend = isrecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.updateTime
     *
     * @return the value of t_blog.updateTime
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.updateTime
     *
     * @param updatetime the value for t_blog.updateTime
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.addTime
     *
     * @return the value of t_blog.addTime
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.addTime
     *
     * @param addtime the value for t_blog.addTime
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.status
     *
     * @return the value of t_blog.status
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.status
     *
     * @param status the value for t_blog.status
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.type_id
     *
     * @return the value of t_blog.type_id
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.type_id
     *
     * @param typeId the value for t_blog.type_id
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.content
     *
     * @return the value of t_blog.content
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.content
     *
     * @param content the value for t_blog.content
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}