package com.july.po;

import java.util.Date;

public class TBlogtype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blogtype.id
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blogtype.typeName
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private String typename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blogtype.num
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blogtype.addTime
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private Date addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blogtype.id
     *
     * @return the value of t_blogtype.id
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blogtype.id
     *
     * @param id the value for t_blogtype.id
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blogtype.typeName
     *
     * @return the value of t_blogtype.typeName
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blogtype.typeName
     *
     * @param typename the value for t_blogtype.typeName
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setTypename(String typename) {
        this.typename = typename == null ? null : typename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blogtype.num
     *
     * @return the value of t_blogtype.num
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blogtype.num
     *
     * @param num the value for t_blogtype.num
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blogtype.addTime
     *
     * @return the value of t_blogtype.addTime
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blogtype.addTime
     *
     * @param addtime the value for t_blogtype.addTime
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }
}