package com.july.po;

import java.util.Date;

public class TLinks {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_links.id
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_links.link
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private String link;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_links.name
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_links.clickNum
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private Integer clicknum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_links.sort
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_links.status
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_links.addTime
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_links.isApply
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private Integer isapply;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_links.id
     *
     * @return the value of t_links.id
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_links.id
     *
     * @param id the value for t_links.id
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_links.link
     *
     * @return the value of t_links.link
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_links.link
     *
     * @param link the value for t_links.link
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_links.name
     *
     * @return the value of t_links.name
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_links.name
     *
     * @param name the value for t_links.name
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_links.clickNum
     *
     * @return the value of t_links.clickNum
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public Integer getClicknum() {
        return clicknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_links.clickNum
     *
     * @param clicknum the value for t_links.clickNum
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setClicknum(Integer clicknum) {
        this.clicknum = clicknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_links.sort
     *
     * @return the value of t_links.sort
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_links.sort
     *
     * @param sort the value for t_links.sort
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_links.status
     *
     * @return the value of t_links.status
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_links.status
     *
     * @param status the value for t_links.status
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_links.addTime
     *
     * @return the value of t_links.addTime
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_links.addTime
     *
     * @param addtime the value for t_links.addTime
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_links.isApply
     *
     * @return the value of t_links.isApply
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public Integer getIsapply() {
        return isapply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_links.isApply
     *
     * @param isapply the value for t_links.isApply
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setIsapply(Integer isapply) {
        this.isapply = isapply;
    }
}