package com.july.po;

import java.util.Date;

public class TVisit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visit.id
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visit.ip
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visit.userAgent
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private String useragent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visit.city
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visit.url
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visit.browserType
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private String browsertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visit.platformType
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private String platformtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visit.time
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visit.id
     *
     * @return the value of t_visit.id
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visit.id
     *
     * @param id the value for t_visit.id
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visit.ip
     *
     * @return the value of t_visit.ip
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visit.ip
     *
     * @param ip the value for t_visit.ip
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visit.userAgent
     *
     * @return the value of t_visit.userAgent
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public String getUseragent() {
        return useragent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visit.userAgent
     *
     * @param useragent the value for t_visit.userAgent
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setUseragent(String useragent) {
        this.useragent = useragent == null ? null : useragent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visit.city
     *
     * @return the value of t_visit.city
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visit.city
     *
     * @param city the value for t_visit.city
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visit.url
     *
     * @return the value of t_visit.url
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visit.url
     *
     * @param url the value for t_visit.url
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visit.browserType
     *
     * @return the value of t_visit.browserType
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public String getBrowsertype() {
        return browsertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visit.browserType
     *
     * @param browsertype the value for t_visit.browserType
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setBrowsertype(String browsertype) {
        this.browsertype = browsertype == null ? null : browsertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visit.platformType
     *
     * @return the value of t_visit.platformType
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public String getPlatformtype() {
        return platformtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visit.platformType
     *
     * @param platformtype the value for t_visit.platformType
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setPlatformtype(String platformtype) {
        this.platformtype = platformtype == null ? null : platformtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visit.time
     *
     * @return the value of t_visit.time
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visit.time
     *
     * @param time the value for t_visit.time
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }
}