package com.july.mapper;

import com.july.po.TBlogtype;
import com.july.po.TBlogtypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBlogtypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blogtype
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    long countByExample(TBlogtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blogtype
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    int deleteByExample(TBlogtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blogtype
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blogtype
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    int insert(TBlogtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blogtype
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    int insertSelective(TBlogtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blogtype
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    List<TBlogtype> selectByExample(TBlogtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blogtype
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    TBlogtype selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blogtype
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") TBlogtype record, @Param("example") TBlogtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blogtype
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    int updateByExample(@Param("record") TBlogtype record, @Param("example") TBlogtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blogtype
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    int updateByPrimaryKeySelective(TBlogtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blogtype
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    int updateByPrimaryKey(TBlogtype record);
}