package com.july.mapper;

import com.july.po.TLinks;
import com.july.po.TLinksExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TLinksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_links
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    long countByExample(TLinksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_links
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    int deleteByExample(TLinksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_links
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_links
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    int insert(TLinks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_links
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    int insertSelective(TLinks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_links
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    List<TLinks> selectByExample(TLinksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_links
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    TLinks selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_links
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") TLinks record, @Param("example") TLinksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_links
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    int updateByExample(@Param("record") TLinks record, @Param("example") TLinksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_links
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    int updateByPrimaryKeySelective(TLinks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_links
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    int updateByPrimaryKey(TLinks record);
}