package com.july.mapper;

import com.july.po.TResource;
import com.july.po.TResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    long countByExample(TResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    int deleteByExample(TResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    int insert(TResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    int insertSelective(TResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    List<TResource> selectByExample(TResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    TResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") TResource record, @Param("example") TResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    int updateByExample(@Param("record") TResource record, @Param("example") TResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    int updateByPrimaryKeySelective(TResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    int updateByPrimaryKey(TResource record);
}