package com.july.mapper;

import com.july.po.TVisit;
import com.july.po.TVisitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TVisitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    long countByExample(TVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    int deleteByExample(TVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    int insert(TVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    int insertSelective(TVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    List<TVisit> selectByExample(TVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    TVisit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") TVisit record, @Param("example") TVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    int updateByExample(@Param("record") TVisit record, @Param("example") TVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    int updateByPrimaryKeySelective(TVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit
     *
     * @mbg.generated Fri Sep 13 16:38:56 CST 2019
     */
    int updateByPrimaryKey(TVisit record);
}